type: object
properties:
   parentMenuId:
      description: "id of the parent menu of this menu item, or -1 for a top-level item"
      type: string
   applicationPageId:
      description: "id of the application page targeted by this menu item, or -1 if there is no targeted page (that is, the item is a parent menu)"
      type: string
   applicationId:
      description: "id of the application related to this menu item"
      type: string
   menuIndex:
      description: "index of the menu item"
      type: string
   displayName:
      description: "label to display for this menu in the application navigation bar or menu"
      type: string
example:
   displayName: "menuLabel"
   applicationId: "1"
   applicationPageId: "5"
   menuIndex: "1"
   parentMenuId: "-1"
